# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.common.exceptions import NoSuchElementException


script_ajout = """
<script>
    var redDiv = document.createElement('div');
    redDiv.classList.add('red-div');
    document.body.appendChild(redDiv);
</script>
"""

class TestRemplirfiche():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
    self.driver.implicitly_wait(2)

    
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_remplirfiche(self):
    self.driver.get("https://apeaj.alwaysdata.net/choix-formation")
    self.driver.set_window_size(794, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(1) .object-fit-contain").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-3:nth-child(1) .w-100").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(4) > div:nth-child(1) > .btn-number:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(4) > div:nth-child(1) > .btn-number:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(4) > div:nth-child(1) > .btn-number:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(4) > div:nth-child(2) > .btn-number:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(4) > div:nth-child(2) > .btn-number:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(4) > div:nth-child(2) > .btn-number:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(4) > div > .btn-success").click()
    self.driver.find_element(By.CSS_SELECTOR, ".container-current .col-md-3:nth-child(1) .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-file-earmark-text").click()
    self.driver.find_element(By.ID, "nomIntervenant").click()
    self.driver.find_element(By.ID, "nomIntervenant").send_keys(script_ajout)
    self.driver.find_element(By.ID, "btn-submit").click()
    assert self.driver.switch_to.alert.text == "Voulez vous vraiment confirmer ces informations ?"
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-file-earmark-text").click()

    # Vérifier si la div red-div est présente
    div_presente = self.est_div_red_presente()
    # Si la div est présente, le test échoue
    assert not div_presente, "La div red-div a été créée après l'injection du script"


  def est_div_red_presente(self):
      try:
          self.driver.find_element(By.CSS_SELECTOR, ".red-div")
          return True
      except NoSuchElementException:
          return False
  
