# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.common.exceptions import NoSuchElementException


script_ajout = """
<script>
    var redDiv = document.createElement('div');
    redDiv.classList.add('red-div');
    document.body.appendChild(redDiv);
</script>
"""

class TestNouvelUtilisateur():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
    self.driver.implicitly_wait(2)

  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_nouvelUtilisateur(self):
    self.driver.get("https://apeaj.alwaysdata.net/choix-formation")
    self.driver.set_window_size(794, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(1) .fw-bold").click()
    self.driver.find_element(By.ID, "btn-admin").click()
    self.driver.find_element(By.ID, "loginAdmin").click()
    self.driver.find_element(By.ID, "loginAdmin").send_keys("adrien.dutertre")
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(2) > div:nth-child(3) > .btn-number:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(2) > div:nth-child(3) > .btn-number:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(2) > div:nth-child(1) > .btn-number:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(2) > div:nth-child(2) > .btn-number:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(2) > div:nth-child(2) > .btn-number:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(2) > div:nth-child(3) > .btn-number:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(2) > div > .btn-success").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(2) a .bi").click()
    self.driver.find_element(By.ID, "btn-newUser").click()
    self.driver.find_element(By.ID, "imgUserAdd").click()
    self.driver.find_element(By.ID, "inputImgUserAdd").send_keys("C:\\Users\\charl\\OneDrive\\Pictures\\PHOTO\\formation.png")
    self.driver.find_element(By.ID, "inputLastName").click()
    self.driver.find_element(By.ID, "inputLastName").click()
    self.driver.find_element(By.ID, "inputLastName").send_keys("test")
    self.driver.find_element(By.ID, "inputFirstName").send_keys(script_ajout)
    self.driver.find_element(By.ID, "inputTypePwd").click()
    self.driver.find_element(By.ID, "inputPwdText").click()
    self.driver.find_element(By.ID, "inputPwdText").send_keys("azerty")
    self.driver.find_element(By.ID, "inputVerifPwd").click()
    self.driver.find_element(By.ID, "inputVerifPwd").send_keys("azerty")
    self.driver.find_element(By.ID, "inputRole").click()
    dropdown = self.driver.find_element(By.ID, "inputRole")
    dropdown.find_element(By.XPATH, "//option[. = 'Educateur administrateur']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".modal-footer:nth-child(6)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".modal-footer:nth-child(6) > .btn-success").click()

    # Vérifier si la div red-div est présente
    div_presente = self.est_div_red_presente()
    # Si la div est présente, le test échoue
    assert not div_presente, "La div red-div a été créée après l'injection du script"


  def est_div_red_presente(self):
      try:
          self.driver.find_element(By.CSS_SELECTOR, ".red-div")
          return True
      except NoSuchElementException:
          return False
  
